import {
  Container,
  Badge,
  Link,
  List,
  ListItem,
  SimpleGrid,
  UnorderedList,
  Heading,
  Center,
} from "@chakra-ui/react"
import Layout from "../../components/layouts/article"
import { ExternalLinkIcon } from "@chakra-ui/icons"
import { Title, WorkImage, Meta } from "../../components/work"
import P from "../../components/paragraph"

const Work = () => (
  <Layout title="Simon">
    <Container>
      <Title>
        Simon Say Game <Badge>2023</Badge>
      </Title>
      <P>
        <Heading as="h4" fontSize={16} my={6}>
          <Center>Description</Center>
        </Heading>
        The Simon Game is a classic memory and pattern recognition game where
        players must repeat a sequence of colors and tones generated by the
        game. The game starts with a simple pattern and becomes progressively
        more challenging as the player successfully replicates each sequence.
      </P>
      <List ml={4} my={4}>
        <ListItem>
          <Meta>Platform</Meta>
          <span>Andriod, IOS, Windows</span>
        </ListItem>
        <ListItem>
          <Meta>Stack</Meta>
          <span>Objective-C, PHP, MongoDB</span>
        </ListItem>
      </List>
      <P>
        <Heading as="h4" fontSize={16} my={6}>
          <Center>Features</Center>
        </Heading>
        <ul>
          <li>Generate random sequences of colors and tones.</li>
          <li>User-friendly interface with interactive buttons.</li>
          <li>Progressive difficulty levels.</li>
          <li>Score tracking to measure the player's performance.</li>
          <li>Option to reset the game and start over.</li>
        </ul>
      </P>

      <Heading as="h4" fontSize={16} my={6}>
        <Center>Images</Center>
      </Heading>

      <WorkImage src="/images/works/simon1.png" alt="simon" />
      <WorkImage src="/images/works/simon2.png" alt="simon" />
    </Container>
  </Layout>
)

export default Work
